version: '3.8'

services:
  browser:
    build:
      context: .
      dockerfile: Dockerfile.chrome.test
    user: "1000:1000"
    ports:
      - "127.0.0.1:5901:5900"
    volumes:
      - ./appuser:/home/appuser
    environment:
      - DISPLAY=:99
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9223/json/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
